# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Resources | Coding Blocks
email: admissions@codingblocks.com
description: > # this means to ignore newlines until "baseurl:"
  Coding Blocks resource hub, find video lectures, codes and other important study material.



baseurl: "/resources" # the subpath of your site, e.g. /blog
url: "https://codingblocks.com" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: Coding Blocks
copyright:
   name: Coding Blocks
   link: 'https://codingblocks.com'

breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-83327907-1

# Comments
disqus-shortname: championswimmer

#social
facebook: https://www.facebook.com/codingblocksindia
quora:
twitter: https://twitter.com/CodingBlocksIN
github: http://github.com/coding-blocks

#facebook like box
fb-app-id: 549480635219583
fb-page-url: https://www.facebook.com/codingblocksindia/
fb-page-title: Coding Blocks

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]
